import {getCookie} from 'cookies-next'
import Head from 'next/head'
import Container from '../components/Container/Container'
import PageController from '../components/PageController/PageController'
import useWithContext from '../hooks/useWithContext'
import useWithLayout from '../hooks/useWithLayout'
import styles from '../styles/Home.module.css'
import {verifySession} from '../utils/verifySession'

function AdminPage(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home is-full has-background-grey-lighter">
        <Container>
          <PageController {...props} />
        </Container>
      </div>
    </div>
  )
}

export async function getServerSideProps({res, req}) {
  const session = await verifySession({req, res})
  if (!session.isValid) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }
  return {
    props: {
      session,
    },
  }
}

export default useWithContext(useWithLayout(AdminPage))
